# escape=`
FROM plugins/base:windows-1909-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone CurseForge" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-curseforge.exe C:/bin/drone-curseforge.exe
ENTRYPOINT [ "C:\\bin\\drone-curseforge.exe" ]
